package projects_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/godinj/drem-orchestrator/internal/projects"
)

// writeFixture writes the given content to the given path under homeDir,
// creating the per-project directory first. Used by state_test to
// bootstrap fixtures without running the full register path.
func writeFixture(t *testing.T, homeDir, projectName, filename, content string) {
	t.Helper()
	dir := filepath.Join(homeDir, ".drem", "projects", projectName)
	require.NoError(t, os.MkdirAll(dir, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(dir, filename), []byte(content), 0o644))
}

// composeFixtureFull is the fixture that exercises every StateSnapshot
// field. Includes DREM_AGENTMON_TOKEN on orch, a ports block, and
// enough structure to prove we're parsing YAML not regex-grepping.
const composeFixtureFull = `# Generated by drem project register
version: "3.9"
services:
  orch:
    image: localhost:5000/drem-orch:latest
    environment:
      DREM_HEADLESS: "1"
      DREM_AGENTMON_TOKEN: "5945505c-1391-4a23-940e-f3781c257789"
    ports:
      - "127.0.0.1:8080:8080"
  agentmon:
    image: localhost:5000/drem-agentmon:latest
    environment:
      DREM_AGENTMON_TOKEN: "5945505c-1391-4a23-940e-f3781c257789"
`

// TestReadStateFromDisk_FullHappyPath asserts that a well-formed
// compose.yml yields the expected SharedToken and ObservedOrchHostPort.
func TestReadStateFromDisk_FullHappyPath(t *testing.T) {
	homeDir := t.TempDir()
	writeFixture(t, homeDir, "drem-orchestrator", "compose.yml", composeFixtureFull)

	snap, err := projects.ReadStateFromDisk(homeDir, "drem-orchestrator")
	require.NoError(t, err)
	require.Equal(t, "5945505c-1391-4a23-940e-f3781c257789", snap.SharedToken)
	require.Equal(t, 8080, snap.ObservedOrchHostPort)
}

// TestReadStateFromDisk_MissingComposeReturnsZero asserts that a
// non-existent compose.yml yields a zero snapshot without error. The
// caller (update CLI) decides fail-closed semantics based on required
// fields.
func TestReadStateFromDisk_MissingComposeReturnsZero(t *testing.T) {
	homeDir := t.TempDir()
	snap, err := projects.ReadStateFromDisk(homeDir, "nonexistent-project")
	require.NoError(t, err)
	require.Empty(t, snap.SharedToken)
	require.Zero(t, snap.ObservedOrchHostPort)
}

// TestReadStateFromDisk_UnparseableYAMLErrors asserts that a broken
// compose.yml surfaces a parse error rather than being silently
// misread as empty. The operator must see the problem before we
// regenerate and overwrite.
func TestReadStateFromDisk_UnparseableYAMLErrors(t *testing.T) {
	homeDir := t.TempDir()
	writeFixture(t, homeDir, "drem-orchestrator", "compose.yml",
		"services:\n  orch: {{ THIS IS NOT YAML }}\n    environment:\n")

	_, err := projects.ReadStateFromDisk(homeDir, "drem-orchestrator")
	require.Error(t, err)
}

// TestReadStateFromDisk_NoTokenKeyIsEmpty asserts that a compose.yml
// without DREM_AGENTMON_TOKEN yields an empty SharedToken without
// error. The caller must refuse to proceed without --regenerate-token
// when SharedToken is empty; this test proves the extractor returns
// the empty string rather than panicking on missing keys.
func TestReadStateFromDisk_NoTokenKeyIsEmpty(t *testing.T) {
	homeDir := t.TempDir()
	writeFixture(t, homeDir, "drem-orchestrator", "compose.yml", `version: "3.9"
services:
  orch:
    environment:
      DREM_HEADLESS: "1"
    ports:
      - "127.0.0.1:8080:8080"
`)
	snap, err := projects.ReadStateFromDisk(homeDir, "drem-orchestrator")
	require.NoError(t, err)
	require.Empty(t, snap.SharedToken)
	require.Equal(t, 8080, snap.ObservedOrchHostPort)
}

// TestReadStateFromDisk_NoPortsBlockIsZero asserts that a compose.yml
// without a ports mapping on orch yields zero ObservedOrchHostPort
// without error.
func TestReadStateFromDisk_NoPortsBlockIsZero(t *testing.T) {
	homeDir := t.TempDir()
	writeFixture(t, homeDir, "drem-orchestrator", "compose.yml", `version: "3.9"
services:
  orch:
    environment:
      DREM_AGENTMON_TOKEN: "token-xyz"
`)
	snap, err := projects.ReadStateFromDisk(homeDir, "drem-orchestrator")
	require.NoError(t, err)
	require.Equal(t, "token-xyz", snap.SharedToken)
	require.Zero(t, snap.ObservedOrchHostPort)
}

// TestReadStateFromDisk_MalformedPortIsZero asserts that a port mapping
// that doesn't parse as "host:container" yields zero
// ObservedOrchHostPort without error. The extractor is defensive;
// drift detection (separate layer) surfaces anomalies to the operator.
func TestReadStateFromDisk_MalformedPortIsZero(t *testing.T) {
	homeDir := t.TempDir()
	writeFixture(t, homeDir, "drem-orchestrator", "compose.yml", `version: "3.9"
services:
  orch:
    environment:
      DREM_AGENTMON_TOKEN: "token-xyz"
    ports:
      - "not-a-port"
`)
	snap, err := projects.ReadStateFromDisk(homeDir, "drem-orchestrator")
	require.NoError(t, err)
	require.Equal(t, "token-xyz", snap.SharedToken)
	require.Zero(t, snap.ObservedOrchHostPort)
}

// TestReadStateFromDisk_EmptyProjectNameErrors asserts that the empty
// project name is rejected as a programming error (matches
// WriteProjectComposeAt's symmetry).
func TestReadStateFromDisk_EmptyProjectNameErrors(t *testing.T) {
	_, err := projects.ReadStateFromDisk(t.TempDir(), "")
	require.Error(t, err)
}
