package docker_test

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", ".."))
}

func TestCSuiteWatcherDockerfileBuildsExistingCommand(t *testing.T) {
	root := repoRoot(t)
	dockerfile := filepath.Join(root, "deploy", "docker", "csuite-watcher.Dockerfile")
	data, err := os.ReadFile(dockerfile)
	if err != nil {
		t.Fatalf("read Dockerfile: %v", err)
	}

	const commandPath = "./cmd/csuite-watcher"
	if !strings.Contains(string(data), commandPath) {
		t.Fatalf("csuite-watcher Dockerfile must build %s", commandPath)
	}

	if _, err := os.Stat(filepath.Join(root, "cmd", "csuite-watcher", "main.go")); err != nil {
		t.Fatalf("Dockerfile references %s, but command source is missing: %v", commandPath, err)
	}
}

func TestCSuitePersonaBuildContractUsesOpenCode(t *testing.T) {
	root := repoRoot(t)
	baseDockerfile := filepath.Join(root, "deploy", "docker", "csuite-base.Dockerfile")
	data, err := os.ReadFile(baseDockerfile)
	if err != nil {
		t.Fatalf("read csuite-base Dockerfile: %v", err)
	}

	content := string(data)
	for _, required := range []string{
		"OpenCode CLI",
		"opencode plugin \"@guard22/opencode-multi-auth-codex@${OPENCODE_MULTI_AUTH_CODEX_VERSION}\"",
		"csuite-persona",
	} {
		if !strings.Contains(content, required) {
			t.Fatalf("csuite-base Dockerfile must document/install %q for the current persona runtime", required)
		}
	}

	if _, err := os.Stat(filepath.Join(root, "cmd", "csuite-persona", "main.go")); err != nil {
		t.Fatalf("csuite-base stages cmd/csuite-persona, but command source is missing: %v", err)
	}
}

func TestMikePromptAllowsStandingTestReviewAuthority(t *testing.T) {
	root := repoRoot(t)
	paths := []string{filepath.Join(root, "docs", "csuite-agents", "prompts", "mike.md")}
	stagedPrompt := filepath.Join(root, "deploy", "docker", "context", "csuite-prompts", "mike.md")
	if _, err := os.Stat(stagedPrompt); err == nil {
		paths = append(paths, stagedPrompt)
	} else if !os.IsNotExist(err) {
		t.Fatalf("stat staged Mike prompt %s: %v", stagedPrompt, err)
	}

	for _, path := range paths {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read Mike prompt %s: %v", path, err)
		}
		content := string(data)
		for _, required := range []string{
			"Gate Authorization Protocol",
			"standing autonomous `test_review` authority",
			"plans/mike-standing-test-review-authority.md",
			"Bare `ops-relay` `status_change` notifications for `plan_review` are visibility",
			"dremctl approve <task-id-prefix>",
			"dremctl reject <task-id-prefix> --reason",
		} {
			if !strings.Contains(content, required) {
				t.Fatalf("Mike prompt %s must contain %q", path, required)
			}
		}
		if strings.Contains(content, "Approve or reject tasks at human gates (other than") {
			t.Fatalf("Mike prompt %s still contains the old absolute gate-action prohibition", path)
		}
	}

	// The Docker context is intentionally generated by build-csuite.sh and is
	// absent in a clean checkout. Prove the canonical prompt is staged by the
	// supported build entry point instead of requiring generated files to be
	// committed before `go test ./...` can pass.
	buildScriptPath := filepath.Join(root, "deploy", "docker", "build-csuite.sh")
	buildScript, err := os.ReadFile(buildScriptPath)
	if err != nil {
		t.Fatalf("read C-Suite build script: %v", err)
	}
	for _, required := range []string{
		`PROMPT_SRC="docs/csuite-agents/prompts"`,
		`PROMPT_DST="deploy/docker/context/csuite-prompts"`,
		`cp "${PROMPT_SRC}/${persona}.md" "${PROMPT_DST}/${persona}.md"`,
	} {
		if !strings.Contains(string(buildScript), required) {
			t.Fatalf("C-Suite build script must stage Mike's canonical prompt via %q", required)
		}
	}
}

func TestWorkerGoDockerfileExposesGoOnLoginShellPath(t *testing.T) {
	root := repoRoot(t)
	dockerfile := filepath.Join(root, "deploy", "docker", "worker-go.Dockerfile")
	data, err := os.ReadFile(dockerfile)
	if err != nil {
		t.Fatalf("read worker-go Dockerfile: %v", err)
	}

	content := string(data)
	for _, required := range []string{
		"gcc",
		"libc6-dev",
		"ln -sf /usr/local/go/bin/go /usr/local/bin/go",
		"ln -sf /usr/local/go/bin/gofmt /usr/local/bin/gofmt",
	} {
		if !strings.Contains(content, required) {
			t.Fatalf("worker-go Dockerfile must expose %q for bash -lc command execution", required)
		}
	}
}

func TestWorkerBaseTrustsOnlyTheMountedBareRepository(t *testing.T) {
	root := repoRoot(t)
	path := filepath.Join(root, "deploy", "docker", "worker-base.Dockerfile")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read worker-base Dockerfile: %v", err)
	}
	contents := string(data)
	if !strings.Contains(contents, "git config --system --add safe.directory /bare") {
		t.Fatal("worker-base must trust the fixed /bare mount for cross-UID macOS hosts")
	}
	if strings.Contains(contents, "safe.directory '*'") || strings.Contains(contents, "safe.directory \"*\"") {
		t.Fatal("worker-base must not disable Git ownership checks globally")
	}
}

func TestWorkerEntrypointWaitsForWatchdogFinalFlush(t *testing.T) {
	root := repoRoot(t)
	path := filepath.Join(root, "deploy", "docker", "context", "worker-entrypoint.sh")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read worker entrypoint: %v", err)
	}
	contents := string(data)
	for _, required := range []string{"run_harness()", "stop_watchdog", "wait \"${WATCHDOG_PID}\""} {
		if !strings.Contains(contents, required) {
			t.Fatalf("worker entrypoint must contain %q", required)
		}
	}
	for _, forbidden := range []string{"exec claude", "exec opencode", "exec codex", "exec drem-direct-agent"} {
		if strings.Contains(contents, forbidden) {
			t.Fatalf("worker entrypoint must supervise the harness, not use %q", forbidden)
		}
	}
}

func TestWorkerEntrypointFeedsCodexPromptToBackgroundedCommand(t *testing.T) {
	root := repoRoot(t)
	path := filepath.Join(root, "deploy", "docker", "context", "worker-entrypoint.sh")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read worker entrypoint: %v", err)
	}
	contents := string(data)
	for _, required := range []string{
		`"$@" < "${HARNESS_STDIN_PATH}" &`,
		`HARNESS_STDIN_PATH="${PROMPT_PATH}" run_harness codex`,
	} {
		if !strings.Contains(contents, required) {
			t.Fatalf("worker entrypoint must contain %q", required)
		}
	}
	if strings.Contains(contents, `run_harness codex "${codex_args[@]}" - < "${PROMPT_PATH}"`) {
		t.Fatal("Codex prompt redirection must be applied to the backgrounded command, not the supervisor function")
	}
}

func TestStaticServiceDockerfilesHonorBuildTargetArchitecture(t *testing.T) {
	root := repoRoot(t)
	files := []string{
		"spawner.Dockerfile",
		"agentmon.Dockerfile",
		"kyle.Dockerfile",
		"docker-query-proxy.Dockerfile",
		"gq.Dockerfile",
	}

	for _, name := range files {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(root, "deploy", "docker", name)
			data, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read %s: %v", name, err)
			}
			contents := string(data)
			for _, required := range []string{"ARG TARGETOS", "ARG TARGETARCH", "GOOS=${TARGETOS}", "GOARCH=${TARGETARCH}"} {
				if !strings.Contains(contents, required) {
					t.Fatalf("%s must contain %q", name, required)
				}
			}
			if strings.Contains(contents, "GOARCH=amd64") {
				t.Fatalf("%s must not hard-code amd64", name)
			}
		})
	}
}
