apiVersion: 1

datasources:
  - name: DremDB
    type: frser-sqlite-datasource
    uid: drem-sqlite
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      path: /var/lib/grafana/drem.db
