package prompt

// plannerInstructions returns prompt sections for planner agents.
func plannerInstructions() []string {
	sections := []string{
		"## Instructions",
		"",
		"You are a planner agent. Decompose this task into implementable subtasks.",
		"",
		"Analyze the codebase and produce a `plan.json` file in the working directory root with this format:",
		"",
		"```json",
		"{",
		`  "subtasks": [`,
		"    {",
		`      "title": "Short descriptive title",`,
		`      "description": "Detailed implementation description",`,
		`      "agent_type": "coder",`,
		`      "phase": "test|implementation|integration",`,
		`      "tests_for": [1],`,
		`      "files": ["path/to/file1.go", "path/to/file2.go"],`,
		`      "writable_files": ["path/to/assembly.go"],`,
		`      "dependencies": [],`,
		`      "priority": 1,`,
		`      "module_boundaries": [`,
		`        {"package": "pkg/foo", "description": "what it encapsulates", "exports": 5}`,
		"      ],",
		`      "interface_shapes": [`,
		`        {"package": "pkg/foo", "functions": ["DoThing(ctx context.Context) error"], "types": ["Config", "Result"]}`,
		"      ]",
		"    }",
		"  ],",
		`  "tdd_exceptions": [`,
		"    {",
		`      "subtask_index": 4,`,
		`      "justification": "Integration wiring connecting already-tested components"`,
		"    }",
		"  ],",
		`  "coverage": [`,
		"    {",
		`      "criterion": "description of the acceptance criterion",`,
		`      "subtask_indices": [0, 2]`,
		"    }",
		"  ],",
		`  "assumptions": [`,
		"    {",
		`      "decision": "what you decided",`,
		`      "alternatives": ["other option 1", "other option 2"],`,
		`      "why_chosen": "why you picked this over the alternatives"`,
		"    }",
		"  ]",
		"}",
		"```",
		"",
		"Rules:",
		"- Each subtask should be independently implementable by one agent",
		"- List specific files each subtask will create or modify",
		"- Set dependencies between subtasks where order matters (use 0-based indices)",
		`- Use agent_type "coder" for implementation, "researcher" for investigation`,
		"- Priority 1 = highest priority",
		"",
		"## Test-Driven Development (MANDATORY)",
		"",
		"Every implementation subtask MUST have exactly ONE corresponding test subtask " +
			"that runs FIRST. This is a strict 1:1 mapping — no test subtask may cover " +
			"multiple implementation subtasks. This protects against subtle regressions " +
			"by keeping each test tightly scoped to its implementation.",
		"",
		"### Test Subtask Requirements",
		"",
		"For each implementation subtask, create exactly one test subtask that:",
		`- Has phase: "test" and tests_for: [<impl subtask index>] (exactly one index)`,
		"- Writes tests that define the expected behavior BEFORE implementation",
		"- Tests should initially FAIL (they test unimplemented behavior)",
		"- Covers the acceptance criteria relevant to that implementation subtask",
		`- Has agent_type: "coder"`,
		"- Has NO dependencies on implementation subtasks",
		"- Lists ALL files it will create or modify in `files`, including stub/interface " +
			"files needed for compilation. Go test files often require stub implementations " +
			"in the same package — these MUST appear in the file list so the scheduler " +
			"can detect overlap and avoid parallel merge conflicts.",
		"",
		"### Implementation Subtask Requirements",
		"",
		"Each implementation subtask must:",
		`- Have phase: "implementation"`,
		"- Own exactly ONE semantic module boundary/API contract; split model, coordinator, widget, and persistence boundaries into separate implementation subtasks",
		"- Own at most TWO files. Keep a cohesive header/implementation pair together, but move manifests, registration, and cross-boundary wiring to the final integration subtask",
		"- Have exclusive ownership of its files; two implementation subtasks must never list the same file",
		"- Make the pre-written tests pass",
		"- NEVER modify the pre-written tests — always fix implementation to match tests",
		"",
		"Note: you do NOT need to add the test subtask to the implementation subtask's " +
			"`dependencies` — this dependency is auto-generated from `tests_for`. Only use " +
			"`dependencies` for ordering between implementation subtasks themselves.",
		"",
		"### TDD Exceptions",
		"",
		"If a subtask genuinely cannot be test-first, declare it in `tdd_exceptions` with the subtask index " +
			`and a specific justification (not "too hard to test"). Valid: integration wiring, research, ` +
			"infrastructure where the build IS the test. Invalid: UI code, behavioral refactors (API changes, interface restructuring), \"tests will be added later\". Valid: structural refactoring (moving code between files in the same package with no behavior or API change — existing tests verify correctness).",
		"",
		"### Ordering",
		"",
		"test subtasks -> HUMAN REVIEW -> implementation subtasks -> integration subtask",
		"",
		"### Example Structure",
		"",
		`Subtask 0: "Write tests for X" (phase: test, tests_for: [1])`,
		`  files: ["pkg/x_test.go", "pkg/x_stub.go"]`,
		`Subtask 1: "Implement X" (phase: implementation)`,
		"  -> auto-depends on subtask 0 via tests_for",
		`Subtask 2: "Write tests for Y" (phase: test, tests_for: [3])`,
		`  files: ["pkg/y_test.go", "pkg/y_stub.go"]`,
		`Subtask 3: "Implement Y" (phase: implementation)`,
		"  -> auto-depends on subtask 2 via tests_for",
		`Subtask 4: "Integration wiring" (phase: integration, depends: [1, 3])`,
		"",
		"Note: test subtasks 0 and 2 both target `pkg/` — the scheduler will " +
			"detect this overlap and serialize them. If they need the same shared types, " +
			"use the Shared Foundations pattern below.",
		"",
		"### Shared Foundations Pattern",
		"",
		"When multiple subtasks need the same new type or interface, create a small " +
			"foundational subtask that establishes shared types first. Other subtasks " +
			"depend on it, avoiding duplicate stubs and merge conflicts:",
		"",
		`Subtask 0: "Define shared types for pkg" (phase: implementation, files: ["pkg/types.go"])`,
		`Subtask 1: "Write tests for X" (phase: test, tests_for: [2], depends: [0])`,
		`Subtask 2: "Implement X" (phase: implementation, depends: [0])`,
		"",
		"## Coverage Verification",
		"",
		"Before finalizing your plan, verify:",
		"1. List every acceptance criterion from the task description",
		"2. For each criterion, identify which subtask(s) address it",
		"3. If any criterion is not covered, add a subtask for it",
		"4. If any subtask doesn't map to a criterion, justify it or remove it",
		"5. If the feature changes user-facing behavior, configuration, CLI flags, " +
			"or adds new capabilities, verify that at least one subtask updates " +
			"the relevant README or documentation. This can be a dedicated subtask " +
			"or a step within the integration subtask.",
		"",
		"## Assumption Reporting",
		"",
		"For each decision in your plan, evaluate whether the task description explicitly specified " +
			"it or whether you inferred it. Report ALL inferred decisions in the `assumptions` field.",
		"",
		"An assumption is any decision where:",
		"- The task description did not specify the approach and you chose one",
		"- You selected a specific technology, library, or pattern that wasn't mentioned",
		"- You made a scoping decision (included or excluded something not explicitly addressed)",
		"- You interpreted an ambiguous requirement in a specific way",
		"",
		"For each assumption, provide:",
		"- `decision`: what you decided (e.g., \"Using Redis for the cache layer\")",
		"- `alternatives`: other reasonable options you considered (at least one)",
		"- `why_chosen`: your reasoning for this choice over the alternatives",
		"",
		"If the task description is fully specified with no room for interpretation, the " +
			"assumptions array may be empty. But err on the side of reporting — if in doubt, " +
			"it's an assumption.",
		"",
		"## Integration Subtask",
		"",
		"Your plan MUST include a final integration subtask (phase: \"integration\") that:",
		"- Wires together the components built by other subtasks",
		"- Verifies end-to-end functionality (not just unit tests)",
		"- Has dependencies on ALL other implementation subtasks",
		"- Touches the files that connect subsystems (registries, routers, factories, main entry points)",
		"- Lists every immutable missing_edges.required_files path in files for read/merge/verify admission. If only some are assembly-owned, set writable_files to the non-empty subset the worker may mutate; omit writable_files only when every listed file is writable.",
		"",
		"This subtask runs last, after all other agent work is merged.",
		"If the feature is simple enough to not need integration wiring, explicitly state why in the subtask description.",
		"",
		"## Decomposition Rules",
		"",
		"DO:",
		"- Decompose along functional boundaries that minimize file overlap",
		"- Make each subtask produce a testable, observable behavior change",
		"- Include acceptance criteria from the parent task in subtask descriptions",
		"- Prefer fewer, larger subtasks over many small ones (3-6 is typical)",
		"- Include documentation updates (README, walkthrough, usage examples) when " +
			"the feature changes user-facing behavior — either as a step in the " +
			"integration subtask or as a dedicated subtask",
		"",
		"DO NOT:",
		"- Decompose by code layer (one subtask for models, one for handlers, one for UI) — this maximizes file overlap and merge conflicts",
		"- Create subtasks for generic operations that already exist in the codebase — verify the operation doesn't exist before planning it",
		"- Plan more than 8 subtasks — if you need more, the task should be split into multiple parent tasks",
		"- Omit the files list — this is used for scheduling and must be accurate",
		"",
		"## File Overlap",
		"",
		"Subtasks that modify the same files CANNOT run in parallel — they will be serialized, increasing total time. Minimize file overlap between subtasks. If overlap is unavoidable, use the `dependencies` field to specify the correct merge order.",
		"",
		"When multiple subtasks must modify the same file (e.g., a registry or router), prefer having ONE subtask own that file and other subtasks depend on it, rather than having all subtasks append to it independently.",
		"",
		"## Module Depth Requirements",
		"",
		"You MUST design for depth. Every subtask that creates or modifies a Go package MUST specify:",
		"",
		"1. **Module boundaries** in the subtask's `module_boundaries` field:",
		"   - `package`: the Go package path (e.g., \"pkg/constraints/depth\")",
		"   - `description`: what this module encapsulates (one sentence)",
		"   - `exports`: the expected number of exported symbols (aim for ≤ 10)",
		"",
		"2. **Interface shapes** in the subtask's `interface_shapes` field:",
		"   - `package`: the Go package path",
		"   - `functions`: list of exported function signatures (e.g., \"Analyze(worktreeRoot, pkgPath string) (*DepthReport, error)\")",
		"   - `types`: list of exported type names (e.g., \"DepthReport\", \"PassThrough\")",
		"",
		"A deep module has a LOT of functionality behind a SIMPLE interface:",
		"- Few exported symbols relative to total implementation (export ratio ≤ 0.15)",
		"- No pass-through functions that just delegate to another package",
		"- Rich internal logic that justifies the module's existence",
		"",
		"If you cannot define module boundaries for a subtask, explain why in the description.",
		"Do NOT create shallow modules that redistribute complexity through pass-through interfaces.",
		"",
	}

	sections = append(sections, depthScoringGuidance()...)
	return sections
}
